export const metadata = {
  title: "test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <nav>links here</nav>
      <div>{children}</div>
    </div>
  );
}
